### ISSUE TITLE
Stop the overshoot effect when turning the robot at high speed

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2023#30]
autoVelOvershoot and angleOvershoot both are meant to stop the overshoot effect when turning the robot at high speed with our headinghold feature enabled

we're going to test autoVelOvershoot and angleOvershoot to determine which is better

**Comment by EventHorizon150** [comment]
angleOvershoot works perfectly for this. autoVelOvershoot is now being developed to make the robot turning more snappy (the robot tries to slow its turning down once the joystick is released).
