### ISSUE TITLE
Limelight retro reflective centering

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2023#4]
Write a command that can auto align the robot to the scoring poles using the Limelight running photon.

- [ ] Implement pole detection (Retro reflective tape) via the limelight photon Vision libraries
- [ ] Create a command that points the robot to a particular pole.
- [ ] Investigate If it is possible to use the poles to score/point at the other game object scoring locations.
- [ ] Investigate the optimal way for drivers to select what pole to center on.

**Comment by plobber** [comment]
Reflective tape height
- Tall node: 3 ft. 5 7/8 in. (~106 cm.)
- Medium node: 1 ft. 10 1/8 in. (~56 cm)
